// Canonical sample data for the whole system. Every portal derives its view from these records,
// so a submission has one code, one author and one state everywhere. Times are Asia/Dhaka.

import { SEED_REPORTS } from "./seed-reports";
import type { AiFinding, Database, Evidence, Profile, Staff, Submission } from "./types";

export const DB_VERSION = 12;

/** Demo password for every seeded account (frontend preview only). */
export const DEMO_PASSWORD = "Alarm@2026";

const t = (date: string, time = "10:00") => `${date}T${time}:00+06:00`;
let ev = 0;
const e = (kind: string, title: string, meta: string): Evidence => ({ id: `EV-${String(++ev).padStart(4, "0")}`, kind, title, meta });

// ── Profiles ────────────────────────────────────────────────────────────────

const profiles: Profile[] = [
  {
    id: "KAR-702438",
    name: "আব্দুল করিম শেখ",
    initial: "আ",
    post: "ওয়ার্ড কাউন্সিলর",
    party: "বাংলাদেশ আওয়ামী লীগ",
    seat: "রাজশাহী-২",
    division: "রাজশাহী",
    district: "রাজশাহী",
    upazila: "রাজশাহী সিটি কর্পোরেশন",
    thana: "বোয়ালিয়া",
    wards: "ওয়ার্ড ১২, ১৪",
    phone: "01711448290",
    nid: "১৯৭৯••••৬৬১২",
    dob: "১২ মার্চ ১৯৭৪",
    email: "karim.sheikh@example.com",
    facebook: "facebook.com/karim.councillor",
    office: "ওয়ার্ড কার্যালয়, বোয়ালিয়া, রাজশাহী",
    since: "২০২১",
    registeredAt: t("2026-09-02", "11:20"),
    account: "Active",
    audit: { code: "AUD-2026-0143", opened: t("2026-09-08") },
  },
  {
    id: "KAR-265917",
    name: "সাবরিনা আক্তার চৌধুরী",
    initial: "সা",
    post: "ওয়ার্ড কাউন্সিলর",
    party: "বাংলাদেশ জাতীয়তাবাদী দল (বিএনপি)",
    seat: "চট্টগ্রাম-৯",
    division: "চট্টগ্রাম",
    district: "চট্টগ্রাম",
    upazila: "চট্টগ্রাম সিটি কর্পোরেশন",
    thana: "কোতোয়ালী",
    wards: "ওয়ার্ড ১৭, ৩২, ৩৪, ৩৫",
    phone: "01819330472",
    nid: "১৯৮৪••••২২৭১",
    dob: "০৩ জুন ১৯৮৪",
    email: "sabrina.chowdhury@example.com",
    facebook: "facebook.com/sabrina.ward32",
    office: "ওয়ার্ড কার্যালয়, জামালখান, চট্টগ্রাম",
    since: "২০২১",
    registeredAt: t("2026-08-28"),
    account: "Active",
    audit: { code: "AUD-2026-0141", opened: t("2026-09-07") },
  },
  {
    id: "KAR-814369",
    name: "মোঃ রফিকুল ইসলাম",
    initial: "র",
    post: "ওয়ার্ড কাউন্সিলর",
    party: "স্বতন্ত্র",
    seat: "ঢাকা-১৪",
    division: "ঢাকা",
    district: "ঢাকা",
    upazila: "ঢাকা উত্তর সিটি কর্পোরেশন",
    thana: "মিরপুর মডেল",
    wards: "ওয়ার্ড ১৩",
    phone: "01552118840",
    nid: "১৯৭৬••••৯০১৪",
    dob: "২০ আগস্ট ১৯৭৬",
    email: "rafiqul.islam@example.com",
    facebook: "facebook.com/rafiqul.ward13",
    office: "ওয়ার্ড ১৩ কার্যালয়, মিরপুর, ঢাকা",
    since: "২০২১",
    registeredAt: t("2026-08-20"),
    account: "Active",
    audit: { code: "AUD-2026-0147", opened: t("2026-09-12") },
  },
  {
    id: "KAR-539021",
    name: "তানভীর হোসেন ভূঁইয়া",
    initial: "তা",
    post: "পৌর মেয়র",
    party: "জাতীয় পার্টি",
    seat: "সিলেট-১",
    division: "সিলেট",
    district: "সিলেট",
    upazila: "সিলেট সিটি কর্পোরেশন",
    thana: "সদর",
    wards: "ওয়ার্ড ৩, ৫, ৭",
    phone: "01711902316",
    nid: "১৯৯১••••২২০৪",
    dob: "১৪ জানুয়ারি ১৯৯১",
    email: "tanvir.bhuiyan@example.com",
    facebook: "facebook.com/tanvir.sylhet",
    office: "বাড়ি ১৭, উপশহর, সদর, সিলেট-৩১০০",
    since: "২০২১",
    registeredAt: t("2026-08-10"),
    account: "Active",
    audit: { code: "AUD-2026-0139", opened: t("2026-08-30") },
  },
  {
    id: "KAR-126784",
    name: "নুসরাত জাহান মীম",
    initial: "নু",
    post: "ইউপি সদস্য",
    party: "বাংলাদেশ আওয়ামী লীগ",
    seat: "খুলনা-৪",
    division: "খুলনা",
    district: "খুলনা",
    upazila: "কুষ্টিয়া সদর",
    thana: "কুষ্টিয়া সদর",
    wards: "ওয়ার্ড ২, ৪",
    phone: "01780664129",
    nid: "১৯৯৩••••৪১৮০",
    dob: "০৯ নভেম্বর ১৯৯৩",
    email: "nusrat.mim@example.com",
    facebook: "facebook.com/nusrat.up",
    office: "বাড়ি ২৩, মজমপুর, কুষ্টিয়া সদর, কুষ্টিয়া-৭০০০",
    since: "২০২২",
    registeredAt: t("2026-08-05"),
    account: "Suspended",
    audit: { code: "AUD-2026-0131", opened: t("2026-08-25") },
  },
  {
    id: "KAR-693152",
    name: "মোঃ জুয়েল রানা",
    initial: "জু",
    post: "ওয়ার্ড কাউন্সিলর",
    party: "বাংলাদেশ আওয়ামী লীগ",
    seat: "ঢাকা-১৭",
    division: "ঢাকা",
    district: "ঢাকা",
    upazila: "গাজীপুর সিটি কর্পোরেশন",
    thana: "গাজীপুর সদর",
    wards: "ওয়ার্ড ২২",
    phone: "01913207755",
    nid: "১৯৮০••••৫৫১৯",
    dob: "২২ ফেব্রুয়ারি ১৯৮০",
    email: "juel.rana@example.com",
    facebook: "facebook.com/juel.ward22",
    office: "ওয়ার্ড ২২ কার্যালয়, গাজীপুর",
    since: "২০২১",
    registeredAt: t("2026-08-18"),
    account: "Active",
    audit: { code: "AUD-2026-0149", opened: t("2026-09-11") },
  },
];

// ── Staff & reviewers ───────────────────────────────────────────────────────

const staff: Staff[] = [
  { id: "KAR-615283", name: "Jahidul Haque", nameBn: "জাহিদুল হক", initials: "JH", phone: "01712440918", email: "jahidul.haque@example.com", nid: "১৯৯০••••৪৩২১", division: "ঢাকা", district: "ঢাকা", upazila: "ঢাকা উত্তর সিটি কর্পোরেশন", thana: "মিরপুর মডেল", seat: "ঢাকা-১৪", wards: "ওয়ার্ড ১১, ১৩", status: "On duty", joined: t("2025-01-12"), completed: 9, device: { app: "v1.8", lastSync: "9 min ago", pending: 0 } },
  { id: "KAR-274906", name: "Shirin Akter", nameBn: "শিরিন আক্তার", initials: "SA", phone: "01815220424", email: "shirin.akter@example.com", nid: "১৯৯২••••১১৮৭", division: "চট্টগ্রাম", district: "চট্টগ্রাম", upazila: "চট্টগ্রাম সিটি কর্পোরেশন", thana: "বাকলিয়া", seat: "চট্টগ্রাম-৯", wards: "ওয়ার্ড ১৭, ৩৪", status: "On duty", joined: t("2025-03-03"), completed: 6, device: { app: "v1.8", lastSync: "22 min ago", pending: 0 } },
  { id: "KAR-839151", name: "Rasel Mahmud", nameBn: "রাসেল মাহমুদ", initials: "RM", phone: "01911330731", email: "rasel.mahmud@example.com", nid: "১৯৮৮••••৫০৯২", division: "সিলেট", district: "সিলেট", upazila: "সিলেট সিটি কর্পোরেশন", thana: "সদর", seat: "সিলেট-১", wards: "ওয়ার্ড ৩, ৫, ৭", status: "On duty", joined: t("2024-06-21"), completed: 14, device: { app: "v1.8", lastSync: "4 min ago", pending: 1 } },
  { id: "KAR-460372", name: "Nazmun Nahar", nameBn: "নাজমুন নাহার", initials: "NN", phone: "01713900209", email: "nazmun.nahar@example.com", nid: "১৯৮৬••••৩৩৪০", division: "ঢাকা", district: "ঢাকা", upazila: "গাজীপুর সিটি কর্পোরেশন", thana: "গাজীপুর সদর", seat: "ঢাকা-১৭", wards: "ওয়ার্ড ৯, ১১", status: "On duty", joined: t("2024-02-08"), completed: 18, device: { app: "v1.8", lastSync: "1 hr ago", pending: 0 } },
  { id: "KAR-193847", name: "Imran Chowdhury", nameBn: "ইমরান চৌধুরী", initials: "IC", phone: "01819554242", email: "imran.chowdhury@example.com", nid: "১৯৯৪••••৭৭১৫", division: "ঢাকা", district: "ঢাকা", upazila: "ঢাকা উত্তর সিটি কর্পোরেশন", thana: "মিরপুর মডেল", seat: "ঢাকা-১৪", wards: "ওয়ার্ড ১১, ১২", status: "Suspended", joined: t("2025-04-15"), completed: 3, device: { app: "v1.6", lastSync: "3 days ago", pending: 4 }, note: "Suspended after repeated late and incomplete uploads — open assignments need reassigning." },
  { id: "KAR-528610", name: "Sumaiya Islam", nameBn: "সুমাইয়া ইসলাম", initials: "SI", phone: "01717270027", email: "sumaiya.islam@example.com", nid: "১৯৯১••••২০৫৮", division: "রাজশাহী", district: "রাজশাহী", upazila: "রাজশাহী সিটি কর্পোরেশন", thana: "বোয়ালিয়া", seat: "রাজশাহী-২", wards: "ওয়ার্ড ১২, ১৪", status: "On duty", joined: t("2024-09-30"), completed: 11, device: { app: "v1.8", lastSync: "15 min ago", pending: 0 } },
  { id: "KAR-947263", name: "Mizanur Rahman", nameBn: "মিজানুর রহমান", initials: "MR", phone: "01816330933", email: "mizanur.rahman@example.com", nid: "১৯৮৯••••৬৬০৩", division: "চট্টগ্রাম", district: "চট্টগ্রাম", upazila: "চট্টগ্রাম সিটি কর্পোরেশন", thana: "কোতোয়ালী", seat: "চট্টগ্রাম-৯", wards: "ওয়ার্ড ৩২, ৩৫", status: "On duty", joined: t("2024-11-11"), completed: 8, device: { app: "v1.8", lastSync: "31 min ago", pending: 0 } },
  { id: "KAR-381054", name: "Ferdous Alam", nameBn: "ফেরদৌস আলম", initials: "FA", phone: "01714150015", email: "ferdous.alam@example.com", nid: "১৯৮৭••••৯০২৬", division: "রংপুর", district: "রংপুর", upazila: "রংপুর সিটি কর্পোরেশন", thana: "সদর", seat: "রংপুর-৩", wards: "ওয়ার্ড ৪, ৬", status: "On leave", joined: t("2024-08-19"), completed: 7, device: { app: "v1.7", lastSync: "4 days ago", pending: 0 }, note: "Approved leave until 28 Sep." },
];

const reviewers: Database["reviewers"] = [
  { id: "KAR-736204", name: "Farhana Yasmin", nameBn: "ফারহানা ইয়াসমিন", initials: "FY", phone: "01755432198", email: "farhana.yasmin@example.com", nid: "১৯৮৫••••৭৭৪১", status: "Active", areas: ["রাজশাহী · বোয়ালিয়া", "চট্টগ্রাম · কোতোয়ালী", "ঢাকা · মিরপুর মডেল"], joined: t("2025-12-01"), history: { decided: 38, accepted: 27, avgHours: 19 } },
  { id: "KAR-158392", name: "Tahmina Rahman", nameBn: "তাহমিনা রহমান", initials: "TR", phone: "01819660709", email: "tahmina.rahman@example.com", nid: "১৯৯০••••২২১৮", status: "Active", areas: ["চট্টগ্রাম · কোতোয়ালী", "চট্টগ্রাম · বাকলিয়া"], joined: t("2026-09-23"), history: { decided: 0, accepted: 0, avgHours: 0 }, note: "Coverage added yesterday — চট্টগ্রাম · কোতোয়ালী is shared with Farhana Yasmin." },
  { id: "KAR-904617", name: "Arif Hossain", nameBn: "আরিফ হোসেন", initials: "AH", phone: "01711110311", email: "arif.hossain@example.com", nid: "১৯৮২••••৯০৩৫", status: "On leave", areas: ["সিলেট · সদর", "রংপুর · সদর"], joined: t("2025-03-14"), history: { decided: 17, accepted: 13, avgHours: 31 }, note: "On leave until 28 Sep — submissions from সিলেট and রংপুর need another reviewer." },
  { id: "KAR-327548", name: "Nasrin Sultana", nameBn: "নাসরিন সুলতানা", initials: "NS", phone: "01913130413", email: "nasrin.sultana@example.com", nid: "১৯৮৮••••৪৪০৬", status: "Active", areas: ["ঢাকা · গাজীপুর সদর", "খুলনা · কুষ্টিয়া সদর"], joined: t("2025-07-02"), history: { decided: 26, accepted: 21, avgHours: 14 } },
];

// ── Submissions ─────────────────────────────────────────────────────────────

type SeedSub = Omit<Submission, "events" | "evidence"> & { evidence: Evidence[] };

/** Builds the event history a seeded submission would have produced. */
function withEvents(s: SeedSub): Submission {
  const submitter = s.origin === "self" ? s.profileId : s.staffId!;
  const events: Submission["events"] = [{ at: s.submittedAt, by: submitter, type: "submitted" }];
  if (s.decidedAt && s.decidedBy) {
    const type = s.state === "Accepted" || s.state === "Withdrawn" ? "accepted" : s.state === "Held" ? "held" : "rejected";
    events.push({ at: s.decidedAt, by: s.decidedBy, type, note: s.reason });
  }
  return { ...s, events };
}

const R4 = "KAR-736204";

const seedSubmissions: SeedSub[] = [
  // KAR-702438 · আব্দুল করিম শেখ — Boalia, collected by KAR-528610; reviewed by KAR-736204.
  {
    code: "SUB-0398",
    profileId: "KAR-702438",
    origin: "staff",
    staffId: "KAR-528610",
    category: "নেতিবাচক",
    title: "বিদেশে অঘোষিত সম্পত্তি রয়েছে বলে অনলাইন দাবি",
    source: "বেনামি ফেসবুক পোস্ট · উৎস যাচাই করা যায়নি",
    body: "একটি বেনামি ফেসবুক পোস্টে বিদেশে অঘোষিত সম্পত্তির দাবি করা হয়েছিল। পোস্টদাতার পরিচয় যাচাই করা যায়নি এবং কোনো নথিগত ভিত্তি পাওয়া যায়নি।",
    facts: [["উৎস", "বেনামি ফেসবুক পোস্ট"], ["যাচাই", "সম্ভব হয়নি"]],
    evidence: [e("স্ক্রিনশট", "ফেসবুক পোস্টের স্ক্রিনশট", "বেনামি অ্যাকাউন্ট · লেখকের পরিচয় নেই")],
    state: "Rejected",
    submittedAt: t("2026-09-08", "09:40"),
    decidedAt: t("2026-09-08", "15:10"),
    decidedBy: R4,
    reason: "বেনামি উৎস — পোস্টদাতার পরিচয় যাচাই করা যায়নি এবং কোনো নথিগত ভিত্তি পাওয়া যায়নি। একই তথ্য আবার জমা দেওয়া যাবে না।",
  },
  {
    code: "SUB-0404",
    profileId: "KAR-702438",
    origin: "staff",
    staffId: "KAR-528610",
    category: "ইতিবাচক",
    title: "ওয়ার্ড পরিষদের ৫২টি সভার মধ্যে ৪৭টিতে উপস্থিতি নথিভুক্ত",
    source: "ওয়ার্ড পরিষদের হাজিরা খাতার অনুলিপি (২০২৪–২০২৬)",
    body: "ওয়ার্ড পরিষদের হাজিরা খাতা অনুযায়ী ২০২৪ থেকে ২০২৬ সময়ে অনুষ্ঠিত ৫২টি সভার মধ্যে ৪৭টিতে উপস্থিতি নথিভুক্ত রয়েছে — উপস্থিতির হার ৯০.৪%। অনুপস্থিত পাঁচটি সভার মধ্যে তিনটির জন্য আগাম ছুটির আবেদন ছিল।",
    facts: [["মোট সভা", "৫২টি"], ["উপস্থিত", "৪৭টি"], ["হার", "৯০.৪%"], ["সময়কাল", "২০২৪–২০২৬"]],
    evidence: [e("ছবি · ৬টি", "হাজিরা খাতার পাতা", "ওয়ার্ড পরিষদ কার্যালয়"), e("নথি · PDF", "সভার কার্যবিবরণী সারসংক্ষেপ", "২০২৪–২০২৬")],
    state: "Accepted",
    submittedAt: t("2026-09-09", "10:30"),
    decidedAt: t("2026-09-09", "16:00"),
    decidedBy: R4,
    reason: "দপ্তরের রেকর্ডে সমর্থিত — হাজিরা খাতা ও কার্যবিবরণী মিলেছে।",
  },
  {
    code: "SUB-0409",
    profileId: "KAR-702438",
    origin: "staff",
    staffId: "KAR-528610",
    category: "নেতিবাচক",
    title: "হলফনামায় ঘোষিত জমি ও দাখিলা রেকর্ডে ০.৩৩ একরের অসঙ্গতি",
    source: "ভূমি অফিসের দাখিলা রেকর্ড, বোয়ালিয়া",
    body: "নির্বাচন কমিশনে জমা দেওয়া হলফনামায় ঘোষিত জমির পরিমাণের সাথে বোয়ালিয়া ভূমি অফিসের দাখিলা রেকর্ডে ০.৩৩ একরের পার্থক্য পাওয়া গেছে। রাজনৈতিক কর্মীকে ০৩ সেপ্টেম্বর লিখিতভাবে জানানো হয়েছিল; নির্ধারিত সময়ে জবাব পাওয়া যায়নি।",
    facts: [["অসঙ্গতি", "০.৩৩ একর"], ["উৎস", "হলফনামা ও দাখিলা রেকর্ড"], ["জবাব চাওয়া", "০৩ সেপ্টেম্বর ২০২৬"], ["জবাব", "পাওয়া যায়নি"]],
    evidence: [e("নথি · PDF", "নির্বাচন কমিশনের হলফনামা", "জমা ২০২১"), e("নথি · ছবি", "ভূমি অফিসের দাখিলা রেকর্ড", "বোয়ালিয়া, সংগ্রহ ০৯ সেপ্টেম্বর"), e("নথি · PDF", "জবাব চেয়ে পাঠানো চিঠি", "০৩ সেপ্টেম্বর · জবাব আসেনি")],
    state: "Accepted",
    submittedAt: t("2026-09-09", "11:15"),
    decidedAt: t("2026-09-09", "17:20"),
    decidedBy: R4,
    reason: "দুটি সরকারি নথিতে অসঙ্গতি সমর্থিত। ব্যক্তিকে জবাবের সুযোগ দেওয়া হয়েছিল; নির্ধারিত সময়ে জবাব আসেনি।",
  },
  {
    code: "SUB-0412",
    profileId: "KAR-702438",
    origin: "staff",
    staffId: "KAR-528610",
    category: "নেতিবাচক",
    title: "ড্রেন নির্মাণ দরপত্রে নিকটাত্মীয়ের মালিকানাধীন প্রতিষ্ঠান নির্বাচিত",
    source: "দরপত্র নথি ২০২৫/১১৮ ও আরজেএসসি মালিকানা রেকর্ড",
    body: "ওয়ার্ড ১২-এর ড্রেন নির্মাণ দরপত্রে (২০২৫/১১৮) নির্বাচিত ঠিকাদারি প্রতিষ্ঠানের মালিকানায় রাজনৈতিক কর্মীর নিকটাত্মীয়ের নাম রয়েছে বলে আরজেএসসি রেকর্ডে পাওয়া গেছে। দরপত্র প্রক্রিয়া উন্মুক্ত ছিল এবং তিনটি প্রতিষ্ঠান অংশ নিয়েছিল। বিধি লঙ্ঘনের প্রমাণ পাওয়া যায়নি, তবে মালিকানার সম্পর্কটি নথিতে নিশ্চিত।",
    facts: [["দরপত্র নম্বর", "২০২৫/১১৮"], ["অংশগ্রহণকারী", "৩টি প্রতিষ্ঠান"], ["সম্পর্ক", "নিকটাত্মীয় · আরজেএসসি নথিভুক্ত"], ["যাচাই", "দুটি স্বতন্ত্র সরকারি নথি"]],
    evidence: [e("নথি · PDF", "দরপত্র মূল্যায়ন নথি ২০২৫/১১৮", "আরসিসি দরপত্র শাখা"), e("নথি · PDF", "আরজেএসসি মালিকানা রেকর্ড", "সংগ্রহ ০৯ সেপ্টেম্বর ২০২৬")],
    state: "Accepted",
    submittedAt: t("2026-09-10", "09:20"),
    decidedAt: t("2026-09-10", "14:40"),
    decidedBy: R4,
    reason: "দরপত্র নথি ও আরজেএসসি রেকর্ড — দুটি স্বতন্ত্র সরকারি সূত্রে নিশ্চিত।",
    response: "দরপত্রটি উন্মুক্ত প্রক্রিয়ায় হয়েছে এবং আমি মূল্যায়ন কমিটিতে ছিলাম না — কমিটির কার্যবিবরণী সংযুক্ত।",
  },
  {
    code: "SUB-0418",
    profileId: "KAR-702438",
    origin: "staff",
    staffId: "KAR-528610",
    category: "ইতিবাচক",
    title: "ওয়ার্ডে ৩টি রাস্তা ও ২টি ড্রেন সংস্কার নির্ধারিত বাজেটে সম্পন্ন",
    source: "সিটি কর্পোরেশনের প্রকল্প সমাপ্তি প্রতিবেদন ও মাঠের ছবি",
    body: "রাজশাহী সিটি কর্পোরেশনের ২০২৫–২৬ অর্থবছরের বার্ষিক উন্নয়ন কর্মসূচির আওতায় ওয়ার্ড ১২ ও ১৪-এ তিনটি সড়ক ও দুটি ড্রেন সংস্কার করা হয়েছে। বরাদ্দ ছিল ৮৪ লক্ষ টাকা; সমাপ্তি প্রতিবেদনে ব্যয় দেখানো হয়েছে ৮১ লক্ষ ৬০ হাজার টাকা। নির্ধারিত সময়ের ১১ দিন আগে কাজ শেষ হয়েছে বলে প্রকৌশল শাখা প্রত্যয়ন করেছে।",
    facts: [["প্রকল্প নম্বর", "RCC/ADP/2025-26/118"], ["বরাদ্দ", "৮৪,০০,০০০ টাকা"], ["সমাপ্তি", "০৪ সেপ্টেম্বর ২০২৬"], ["যাচাই", "মাঠ পরিদর্শন + দপ্তরের নথি"]],
    evidence: [e("ছবি · ৪টি", "সংস্কার শেষে সড়কের ছবি", "মাঠ পরিদর্শন, ০৪ সেপ্টেম্বর"), e("নথি · PDF", "প্রকল্প সমাপ্তি প্রতিবেদন", "আরসিসি প্রকৌশল শাখা, ০৪ সেপ্টেম্বর"), e("নথি · PDF", "বরাদ্দপত্র ও ব্যয় বিবরণী", "আরসিসি হিসাব শাখা")],
    state: "Accepted",
    submittedAt: t("2026-09-10", "10:05"),
    decidedAt: t("2026-09-10", "16:30"),
    decidedBy: R4,
    reason: "প্রকল্প নথি ও বরাদ্দপত্র যাচাই করা হয়েছে; মাঠের ছবিতে কাজ সম্পন্ন দেখা যায়।",
  },
  {
    code: "SUB-0421",
    profileId: "KAR-702438",
    origin: "staff",
    staffId: "KAR-528610",
    category: "নেতিবাচক",
    title: "জলাশয় ভরাটের অনুমোদন প্রক্রিয়ায় সুপারিশকারী হিসেবে সম্পৃক্ততা",
    source: "পরিবেশ অধিদপ্তরের আদেশ, ২২ জুলাই ২০২৫",
    body: "জলাশয় ভরাট করে নির্মিত একটি স্থাপনার অনুমোদন প্রক্রিয়ায় সুপারিশকারী হিসেবে স্বাক্ষরের অভিযোগ। পরিবেশ অধিদপ্তর ২০২৫ সালের জুলাইয়ে স্থাপনাটিকে অবৈধ ঘোষণা করে।",
    facts: [["আদেশ", "পরিবেশ অধিদপ্তর, ২২ জুলাই ২০২৫"], ["ভূমিকা", "সুপারিশকারী"], ["সূত্র", "সরকারি নথি"]],
    evidence: [e("নথি · PDF", "পরিবেশ অধিদপ্তরের আদেশ", "২২ জুলাই ২০২৫"), e("ছবি · ২টি", "স্থাপনা ও ভরাটকৃত জলাশয়", "মাঠ পরিদর্শনে তোলা")],
    state: "Pending",
    submittedAt: t("2026-09-21", "11:40"),
  },
  {
    code: "SUB-0422",
    profileId: "KAR-702438",
    origin: "staff",
    staffId: "KAR-528610",
    category: "ইতিবাচক",
    title: "২০২৪ সালের বন্যায় ২১০টি পরিবারকে ত্রাণ সহায়তা",
    source: "দৈনিক সোনার দেশ, ২২ জুলাই ২০২৪ · একটি সংবাদ সূত্র",
    body: "২০২৪ সালের বন্যায় ওয়ার্ড ১৪-এর ২১০টি পরিবারকে ত্রাণ সহায়তা দেওয়ার সংবাদ প্রতিবেদন। বিতরণ তালিকা এখনও সংগ্রহ করা যায়নি।",
    facts: [["পরিবার", "২১০টি"], ["সময়", "জুলাই ২০২৪"], ["সূত্র", "একটি সংবাদপত্র"]],
    evidence: [e("সংবাদ · ছবি", "দৈনিক সোনার দেশের কাটিং", "২২ জুলাই ২০২৪ · একক সূত্র")],
    state: "Pending",
    submittedAt: t("2026-09-22", "15:10"),
  },
  {
    code: "SUB-0428",
    profileId: "KAR-702438",
    origin: "self",
    category: "ইতিবাচক",
    title: "ওয়ার্ড ১৪-এ ২০০ মিটার নতুন পানির লাইন স্থাপন",
    source: "ওয়াসার কার্যাদেশ ও কাজ শেষের ছবি সংযুক্ত",
    body: "ওয়ার্ড ১৪-এর সাগরপাড়া এলাকায় ২০০ মিটার নতুন পানির লাইন স্থাপন করা হয়েছে। ওয়াসার কার্যাদেশ ও কাজ শেষের ছবি সংযুক্ত করা হয়েছে।",
    facts: [["দৈর্ঘ্য", "২০০ মিটার"], ["এলাকা", "সাগরপাড়া, ওয়ার্ড ১৪"]],
    evidence: [e("ছবি · ৩টি", "কাজ শেষের ছবি", "রাজনৈতিক কর্মীর আপলোড"), e("নথি · PDF", "ওয়াসার কার্যাদেশ", "১৯ সেপ্টেম্বর")],
    state: "Pending",
    submittedAt: t("2026-09-23", "10:20"),
  },

  // KAR-265917 · সাবরিনা আক্তার চৌধুরী — Kotwali, collected by KAR-274906 and KAR-947263.
  {
    code: "SUB-0399",
    profileId: "KAR-265917",
    origin: "staff",
    staffId: "KAR-274906",
    category: "ইতিবাচক",
    title: "ওয়ার্ড পরিষদের ৫২টি সভার মধ্যে ৪৭টিতে কাউন্সিলরের উপস্থিতি নথিভুক্ত",
    source: "ওয়ার্ড পরিষদের হাজিরা খাতার অনুলিপি",
    body: "ওয়ার্ড পরিষদ কার্যালয় থেকে ২০২৪ থেকে ২০২৬ সময়ের সভার হাজিরা খাতার অনুলিপি সংগ্রহ করা হয়েছে। সচিব উপস্থিত ছিলেন এবং অনুলিপিতে সিল দিয়েছেন। মোট ৫২টি সভার মধ্যে কাউন্সিলরের উপস্থিতি ৪৭টিতে নথিভুক্ত।",
    facts: [["মোট সভা", "৫২টি"], ["উপস্থিত", "৪৭টি"]],
    evidence: [e("নথি", "ওয়ার্ড পরিষদের সভার হাজিরা খাতার অনুলিপি", "08 Sep, 09:40"), e("ছবি", "কার্যালয়ের প্রবেশপথ ও সাইনবোর্ডের ছবি", "08 Sep, 09:52")],
    state: "Accepted",
    submittedAt: t("2026-09-08", "10:14"),
    decidedAt: t("2026-09-08", "11:30"),
    decidedBy: R4,
    reason: "Office seal and register page numbers are continuous, no gaps in the copied range.",
    field: {
      task: "ওয়ার্ড পরিষদের হাজিরা নথি সংগ্রহ",
      visitTime: "০৯:৪০ – ১০:০৫ (২৫ মিনিট)",
      device: "Android · app v1.8 · online",
      checks: [
        { status: "ok", label: "Capture times inside visit window", detail: "Both items captured between 09:40 and 09:52." },
        { status: "ok", label: "Device registered to staff", detail: "KAR-274906 · same device as previous submissions." },
        { status: "ok", label: "No duplicate uploads", detail: "File hashes are unique across the audit." },
      ],
    },
  },
  {
    code: "SUB-0400",
    profileId: "KAR-265917",
    origin: "staff",
    staffId: "KAR-947263",
    category: "নেতিবাচক",
    title: "ড্রেন নির্মাণ দরপত্রে ঠিকাদারের মালিকানা ও হলফনামার তথ্য যাচাই",
    source: "প্রকল্প বোর্ড, দরপত্র নথি ও আরজেএসসি মালিকানা রেকর্ড",
    body: "জামালখানে ড্রেন নির্মাণ প্রকল্পের কাজ সম্পন্ন অবস্থায় পাওয়া গেছে। প্রকল্প বোর্ডে উল্লিখিত ঠিকাদারি প্রতিষ্ঠানের নাম ও কাজের মেয়াদ দরপত্র নথির সাথে মিলে গেছে। ঠিকাদারি প্রতিষ্ঠানের মালিকানায় কাউন্সিলরের পরিবারের সদস্যের নাম আরজেএসসি রেকর্ডে পাওয়া গেছে।",
    facts: [["প্রকল্প", "ড্রেন নির্মাণ, জামালখান"], ["সম্পর্ক", "পরিবারের সদস্য · আরজেএসসি নথিভুক্ত"]],
    evidence: [e("ছবি", "প্রকল্প বোর্ড ও সম্পন্ন কাজের ছবি", "08 Sep, 10:02"), e("হলফনামা", "নির্বাচন কমিশনে জমা হলফনামা ও সম্পদ বিবরণী", "08 Sep, 10:18"), e("দরপত্র নথি", "ঠিকাদারি প্রতিষ্ঠানের মালিকানা নথি (আরজেএসসি)", "08 Sep, 14:10")],
    state: "Accepted",
    submittedAt: t("2026-09-08", "10:41"),
    decidedAt: t("2026-09-08", "12:05"),
    decidedBy: R4,
    reason: "Project board, tender file and affidavit copy agree on contractor name and dates.",
    field: {
      task: "ড্রেন নির্মাণ প্রকল্প এলাকা পরিদর্শন",
      visitTime: "১০:০২ – ১০:৩৫ (৩৩ মিনিট)",
      device: "Android · app v1.8 · online",
      checks: [
        { status: "warn", label: "One item captured after the visit window", detail: "The RJSC ownership file was uploaded at 14:10, outside the 10:02–10:35 window. Staff noted it was collected from the RJSC office the same day." },
        { status: "ok", label: "Device registered to staff", detail: "KAR-947263 · same device as previous submissions." },
        { status: "ok", label: "No duplicate uploads", detail: "File hashes are unique across the audit." },
      ],
    },
  },
  {
    code: "SUB-0401",
    profileId: "KAR-265917",
    origin: "staff",
    staffId: "KAR-274906",
    category: "নেতিবাচক",
    title: "প্রকল্প এলাকা পরিদর্শন ও স্থানীয় বাসিন্দার বক্তব্য",
    source: "প্রকল্প এলাকার ভিডিও ও স্থানীয় বাসিন্দার বক্তব্য",
    body: "স্থানীয় বাসিন্দা মোঃ সেলিম উদ্দিন বক্তব্য দিয়েছেন। তিনি প্রকল্পের কাজ সম্পন্ন হওয়ার কথা নিশ্চিত করেছেন, তবে ঠিকাদার নির্বাচন প্রক্রিয়া নিয়ে তাঁর বক্তব্য দরপত্র নথির তথ্যের সাথে মিলেছে। বক্তব্য গ্রহণের আগে সম্মতি রেকর্ড করা হয়েছে।",
    facts: [["বক্তা", "মোঃ সেলিম উদ্দিন"], ["সম্মতি", "রেকর্ড করা হয়েছে"]],
    evidence: [e("ভিডিও", "প্রকল্প এলাকা পরিদর্শনের ভিডিও", "08 Sep, 16:41"), e("বক্তব্য", "স্থানীয় বাসিন্দার বক্তব্য — মোঃ সেলিম উদ্দিন", "08 Sep, 17:05")],
    state: "Accepted",
    submittedAt: t("2026-09-08", "17:22"),
    decidedAt: t("2026-09-10", "11:10"),
    decidedBy: R4,
    reason: "The statement matches the tender file already on record, so it corroborates SUB-0400.",
    field: {
      task: "স্থানীয় বাসিন্দার বক্তব্য গ্রহণ",
      visitTime: "১৬:৪১ – ১৭:১০ (২৯ মিনিট)",
      device: "Android · app v1.8 · synced offline queue",
      checks: [
        { status: "ok", label: "Consent recorded before statement", detail: "Audio consent captured at 17:03, before the statement began." },
        { status: "warn", label: "Uploaded from the offline queue", detail: "Captured offline and synced at 17:22; original capture times preserved." },
        { status: "ok", label: "Device registered to staff", detail: "KAR-274906 · same device as previous submissions." },
      ],
    },
  },
  {
    code: "SUB-0403",
    profileId: "KAR-265917",
    origin: "staff",
    staffId: "KAR-947263",
    category: "নেতিবাচক",
    title: "উৎসবিহীন অনুদান বিতরণের তালিকা",
    source: "অনুদান বিতরণের তালিকা · উৎস অনিশ্চিত",
    body: "অনুদান বিতরণের একটি তালিকা সংগ্রহ করা হয়েছে, তবে তালিকায় কোনো ইস্যুকারী কার্যালয়ের নাম, সিল বা তারিখ নেই। যিনি তালিকাটি দিয়েছেন তিনি পরিচয় প্রকাশে রাজি হননি।",
    facts: [["উৎস", "অজ্ঞাত"], ["সিল / তারিখ", "নেই"]],
    evidence: [e("নথি", "অনুদান বিতরণের তালিকা — উৎস অনিশ্চিত", "09 Sep, 09:12")],
    state: "Held",
    submittedAt: t("2026-09-09", "09:28"),
    decidedAt: t("2026-09-09", "09:55"),
    decidedBy: R4,
    reason: "The document has no issuing office and the provider is unidentified, so it cannot enter the evidence set as a finding.",
    field: {
      task: "অনুদান বিতরণের তালিকা সংগ্রহ",
      visitTime: "০৯:১২ – ০৯:২০ (৮ মিনিট)",
      device: "Android · app v1.8 · online",
      checks: [
        { status: "bad", label: "Document has no issuing authority", detail: "No office name, seal or date. Cannot be attributed to a source." },
        { status: "bad", label: "Provider unidentified", detail: "The person supplying the list declined to be named, so the chain of custody is broken." },
        { status: "ok", label: "Device registered to staff", detail: "KAR-947263 · same device as previous submissions." },
      ],
    },
  },

  // KAR-814369 · মোঃ রফিকুল ইসলাম — Mirpur, collected by KAR-615283 (and earlier KAR-193847).
  {
    code: "SUB-0395",
    profileId: "KAR-814369",
    origin: "staff",
    staffId: "KAR-193847",
    category: "ইতিবাচক",
    title: "ওয়ার্ড ১৩-এ কমিউনিটি ক্লিনিকের সংস্কার সম্পন্ন",
    source: "সিটি কর্পোরেশনের কার্যাদেশ ও সমাপ্তি সনদ",
    body: "ওয়ার্ড ১৩-এর কমিউনিটি ক্লিনিকের সংস্কার কাজ নির্ধারিত সময়ে সম্পন্ন হয়েছে। কার্যাদেশ ও সমাপ্তি সনদ সংগ্রহ করা হয়েছে।",
    facts: [["প্রকল্প", "কমিউনিটি ক্লিনিক সংস্কার"], ["সমাপ্তি", "আগস্ট ২০২৬"]],
    evidence: [e("নথি · PDF", "কার্যাদেশ", "ডিএনসিসি প্রকৌশল শাখা"), e("নথি · PDF", "সমাপ্তি সনদ", "ডিএনসিসি")],
    state: "Accepted",
    submittedAt: t("2026-09-06", "12:00"),
    decidedAt: t("2026-09-07", "10:30"),
    decidedBy: R4,
    reason: "কার্যাদেশ ও সমাপ্তি সনদ — দুটি দাপ্তরিক নথিতে সমর্থিত।",
  },
  {
    code: "SUB-0430",
    profileId: "KAR-814369",
    origin: "staff",
    staffId: "KAR-615283",
    category: "ইতিবাচক",
    title: "ওয়ার্ড কার্যালয়ের হাজিরা খাতার ছবি",
    source: "হাজিরা খাতা ২০২৪–২০২৬ · ৬টি ছবি সংযুক্ত",
    body: "ওয়ার্ড ১৩ কার্যালয়ের হাজিরা খাতা থেকে ২০২৪–২০২৬ সময়ের সভার উপস্থিতির পাতাগুলোর ছবি নেওয়া হয়েছে। কার্যালয়ের সচিব খাতাটি দেখাতে সম্মত হয়েছেন।",
    facts: [["সময়কাল", "২০২৪–২০২৬"], ["সংগ্রহ", "ওয়ার্ড ১৩ কার্যালয়"]],
    evidence: [e("ছবি · ৬টি", "হাজিরা খাতার পাতা", "ওয়ার্ড ১৩ কার্যালয়"), e("ছবি", "কার্যালয়ের সাইনবোর্ড", "মাঠ পরিদর্শনে তোলা")],
    state: "Pending",
    submittedAt: t("2026-09-21", "13:05"),
  },
  {
    code: "SUB-0431",
    profileId: "KAR-814369",
    origin: "staff",
    staffId: "KAR-615283",
    category: "নেতিবাচক",
    title: "হলফনামার সম্পদ বিবরণী ও দাখিলা রেকর্ডের তুলনা",
    source: "ভূমি অফিস ও নির্বাচন কমিশনের নথি · ৪টি সংযুক্ত",
    body: "নির্বাচন কমিশনে জমা দেওয়া হলফনামার সম্পদ বিবরণীর সাথে মিরপুর ভূমি অফিসের দাখিলা রেকর্ড মিলিয়ে দেখা হয়েছে। দুটি দাগে ঘোষিত পরিমাণের চেয়ে বেশি জমি রেকর্ডে পাওয়া গেছে। নথিগুলো ১৪ সেপ্টেম্বর ২০২৬ সংগ্রহ করা।",
    facts: [["দাগ", "৪১২ ও ৪১৯"], ["সংগ্রহ", "১৪ সেপ্টেম্বর ২০২৬"]],
    evidence: [e("নথি · PDF", "নির্বাচন কমিশনের হলফনামা", "জমা ২০২১"), e("নথি · ছবি", "ভূমি অফিসের দাখিলা রেকর্ড", "মিরপুর, সংগ্রহ ১৪ সেপ্টেম্বর"), e("নথি · ছবি", "খতিয়ানের অনুলিপি", "দাগ ৪১২ ও ৪১৯"), e("নথি · PDF", "তুলনামূলক হিসাব", "তদন্ত সম্পাদকের প্রস্তুত করা")],
    state: "Pending",
    submittedAt: t("2026-09-21", "13:30"),
  },

  // KAR-539021 · তানভীর হোসেন ভূঁইয়া — Sylhet, collected by KAR-839151 (basis of RPT-2026-0039).
  ...(
    [
      ["SUB-0371", "ইতিবাচক", "ওয়ার্ডে ২০২১–২০২৬ সময়ে ৭টি উন্নয়ন প্রকল্প নির্ধারিত বাজেটে সম্পন্ন", "ওয়ার্ড উন্নয়ন প্রকল্প নথি, সিলেট সিটি কর্পোরেশন", "2026-09-01"],
      ["SUB-0374", "ইতিবাচক", "আয়কর রিটার্ন নিয়মিত দাখিল, হলফনামার সাথে সঙ্গতিপূর্ণ", "এনবিআর কর রিটার্ন সারসংক্ষেপ ও হলফনামা", "2026-09-02"],
      ["SUB-0377", "ইতিবাচক", "ওয়ার্ড পরিষদের ৫২টি সভার মধ্যে ৪৭টিতে উপস্থিতি নথিভুক্ত", "ওয়ার্ড পরিষদের সভার হাজিরা খাতা", "2026-09-02"],
      ["SUB-0379", "ইতিবাচক", "আদালতের নথিতে কোনো বিরূপ এন্ট্রি পাওয়া যায়নি", "জেলা জজ আদালতের নথি অনুসন্ধান, সিলেট", "2026-09-02"],
      ["SUB-0383", "নেতিবাচক", "সড়ক সংস্কার দরপত্রে নিকটাত্মীয়ের প্রতিষ্ঠান নির্বাচিত", "দরপত্র নথি ও আরজেএসসি মালিকানা রেকর্ড", "2026-09-02"],
      ["SUB-0386", "নেতিবাচক", "হলফনামা ও দাখিলা রেকর্ডে ০.৪১ একরের অসঙ্গতি", "ভূমি অফিসের দাখিলা রেকর্ড, সিলেট সদর", "2026-09-15"],
      ["SUB-0388", "নেতিবাচক", "জলাশয় ভরাটের অনুমোদনে সুপারিশকারী হিসেবে সম্পৃক্ততা", "পরিবেশ অধিদপ্তরের আদেশ ও মাঠের ছবি", "2026-09-03"],
    ] as const
  ).map(([code, category, title, source, date]) =>
    ({
      code,
      profileId: "KAR-539021",
      origin: "staff",
      staffId: "KAR-839151",
      category,
      title,
      source,
      body: `${title}। ${source} থেকে যাচাই করা হয়েছে।`,
      facts: [["সূত্র", source]],
      evidence: [e("নথি · PDF", source, "সংগ্রহ সেপ্টেম্বর ২০২৬")],
      state: "Accepted",
      submittedAt: t(date, "11:00"),
      decidedAt: t(date, "17:00"),
      decidedBy: "KAR-904617",
      reason: "দাপ্তরিক নথিতে সমর্থিত।",
    }) satisfies SeedSub,
  ),

  // KAR-126784 · নুসরাত জাহান মীম — Kushtia (basis of RPT-2026-0038).
  ...(
    [
      ["SUB-0361", "ইউনিয়নে ৪টি গ্রামীণ সড়ক ও একটি কালভার্ট নির্ধারিত বাজেটে সম্পন্ন", "ইউনিয়ন পরিষদের প্রকল্প সমাপ্তি প্রতিবেদন"],
      ["SUB-0362", "ইউনিয়ন পরিষদের ৩৬টি সভার মধ্যে ৩৪টিতে উপস্থিতি নথিভুক্ত", "ইউনিয়ন পরিষদের হাজিরা খাতা"],
      ["SUB-0363", "ভিজিডি উপকারভোগীর তালিকা উন্মুক্ত সভায় প্রকাশ ও যাচাই", "উন্মুক্ত সভার কার্যবিবরণী ও ভিজিডি তালিকা"],
      ["SUB-0364", "আয়কর রিটার্ন নিয়মিত দাখিল এবং হলফনামার সাথে সঙ্গতিপূর্ণ", "এনবিআর রেকর্ড ও নির্বাচন কমিশনের হলফনামা"],
      ["SUB-0366", "আদালতের নথিতে কোনো বিরূপ এন্ট্রি পাওয়া যায়নি", "জেলা জজ আদালতের নথি অনুসন্ধান, কুষ্টিয়া"],
    ] as const
  ).map(([code, title, source]) =>
    ({
      code,
      profileId: "KAR-126784",
      origin: "staff",
      staffId: "KAR-274906",
      category: "ইতিবাচক",
      title,
      source,
      body: `${title}। ${source} থেকে যাচাই করা হয়েছে।`,
      facts: [["সূত্র", source]],
      evidence: [e("নথি · PDF", source, "সংগ্রহ সেপ্টেম্বর ২০২৬")],
      state: "Accepted",
      submittedAt: t("2026-09-03", "11:00"),
      decidedAt: t("2026-09-04", "12:00"),
      decidedBy: "KAR-327548",
      reason: "দাপ্তরিক নথিতে সমর্থিত।",
    }) satisfies SeedSub,
  ),
  {
    code: "SUB-0391",
    profileId: "KAR-126784",
    origin: "staff",
    staffId: "KAR-274906",
    category: "ইতিবাচক",
    title: "ত্রাণ বিতরণের সংবাদ প্রতিবেদন",
    source: "দৈনিক পত্রিকার কাটিং · একক সূত্র",
    body: "ত্রাণ বিতরণ সংক্রান্ত একটি সংবাদ প্রতিবেদন জমা দেওয়া হয়েছিল। সংবাদটি ছাড়া বিতরণ তালিকা বা দপ্তরের কোনো নথি সংযুক্ত করা হয়নি।",
    facts: [["সূত্র", "একটি সংবাদপত্র"]],
    evidence: [e("সংবাদ · ছবি", "দৈনিক পত্রিকার কাটিং", "০৫ সেপ্টেম্বর · একক সূত্র")],
    state: "Rejected",
    submittedAt: t("2026-09-05", "10:00"),
    decidedAt: t("2026-09-05", "16:00"),
    decidedBy: "KAR-327548",
    reason: "কেবল একটি সংবাদ সূত্র, কোনো দাপ্তরিক নথি সংযুক্ত হয়নি।",
  },

  // KAR-693152 · মোঃ জুয়েল রানা — Gazipur, collected by KAR-615283; reviewed by KAR-327548.
  {
    code: "SUB-0426",
    profileId: "KAR-693152",
    origin: "staff",
    staffId: "KAR-615283",
    category: "ইতিবাচক",
    title: "সড়ক সংস্কার প্রকল্প সম্পন্ন — ওয়ার্ড ২২",
    source: "গাজীপুর সিটি কর্পোরেশনের সমাপ্তি প্রতিবেদন ও মাঠের ছবি",
    body: "ওয়ার্ড ২২-এর দুটি সড়ক সংস্কার প্রকল্প সরেজমিনে পরিদর্শন করা হয়েছে। প্রকল্প সাইনবোর্ড, সমাপ্ত সড়কের ছবি ও সিটি কর্পোরেশনের সমাপ্তি প্রতিবেদন সংযুক্ত।",
    facts: [["প্রকল্প", "দুটি সড়ক সংস্কার"], ["সমাপ্তি", "১২ সেপ্টেম্বর ২০২৬"]],
    evidence: [e("ছবি · ৫টি", "সমাপ্ত সড়ক ও সাইনবোর্ড", "মাঠ পরিদর্শনে তোলা"), e("নথি · PDF", "প্রকল্প সমাপ্তি প্রতিবেদন", "গাজীপুর সিটি কর্পোরেশন")],
    state: "Accepted",
    submittedAt: t("2026-09-13", "09:30"),
    decidedAt: t("2026-09-13", "15:20"),
    decidedBy: "KAR-327548",
    reason: "প্রকল্প সমাপ্তি প্রতিবেদন ও মাঠের ছবিতে তথ্যটি সমর্থিত।",
  },
  {
    code: "SUB-0427",
    profileId: "KAR-693152",
    origin: "staff",
    staffId: "KAR-615283",
    category: "নেতিবাচক",
    title: "প্রকল্পের কাজের গুণগত মান নিয়ে স্থানীয় অভিযোগ",
    source: "২টি ছবি ও একটি বক্তব্য সংযুক্ত",
    body: "প্রকল্পের কাজের গুণগত মান নিয়ে স্থানীয় বাসিন্দাদের অভিযোগ। দুইজনের বক্তব্য রেকর্ড করা হয়েছে; দাপ্তরিক কোনো নথি এখনও সংযুক্ত হয়নি।",
    facts: [["বক্তব্য", "২ জন বাসিন্দা"], ["দাপ্তরিক নথি", "নেই"]],
    evidence: [e("ছবি · ২টি", "সড়কের বর্তমান অবস্থা", "মাঠ পরিদর্শনে তোলা"), e("অডিও", "স্থানীয় বাসিন্দার বক্তব্য", "৪ মিনিট ১২ সেকেন্ড")],
    state: "Pending",
    submittedAt: t("2026-09-24", "09:15"),
  },
];

const submissions: Submission[] = seedSubmissions.map(withEvents);

// ── Everything else ─────────────────────────────────────────────────────────

const aiFindings: AiFinding[] = [
  { id: "AI-01", profileId: "KAR-702438", category: "ইতিবাচক", title: "গত পাঁচ বছরের আয়কর রিটার্ন নিয়মিত দাখিল, হলফনামার সাথে সঙ্গতিপূর্ণ", meta: "এনবিআর রেকর্ড ও নির্বাচন কমিশনের হলফনামা · এআই কর্তৃক প্রাপ্ত", sources: 2, suggested: "keep" },
  { id: "AI-02", profileId: "KAR-702438", category: "ইতিবাচক", title: "জেলা জজ আদালতের দেওয়ানি ও ফৌজদারি নথিতে কোনো বিরুপ এন্ট্রি নেই", meta: "সুপ্রিম কোর্ট কজলিস্ট অনুসন্ধান · এআই কর্তৃক প্রাপ্ত", sources: 1, suggested: "keep" },
  { id: "AI-03", profileId: "KAR-702438", category: "ইতিবাচক", title: "২০২৪ সালের বন্যায় ২১০টি পরিবারকে ত্রাণ সহায়তার সংবাদ প্রতিবেদন", meta: "দৈনিক সোনার দেশ, ২২ জুলাই ২০২৪ · একক সংবাদ সূত্র", sources: 1, suggested: "exclude" },
  { id: "AI-04", profileId: "KAR-702438", category: "নেতিবাচক", title: "জলাশয় ভরাটের অনুমোদন প্রক্রিয়ায় সুপারিশকারী হিসেবে সম্পৃক্ততা", meta: "পরিবেশ অধিদপ্তরের আদেশ, ২২ জুলাই ২০২৫ · এআই কর্তৃক প্রাপ্ত", sources: 1, suggested: "keep" },
  { id: "AI-05", profileId: "KAR-702438", category: "নেতিবাচক", title: "২০২৫ সালের একটি রাজনৈতিক সংঘর্ষে সম্পৃক্ততার অভিযোগে সংবাদ প্রতিবেদন", meta: "দৈনিক সোনার দেশ, ১৪ মার্চ ২০২৫ · অভিযোগ, আদালতের কোনো নথি নেই", sources: 1, suggested: "exclude" },
  { id: "AI-06", profileId: "KAR-265917", category: "ইতিবাচক", title: "নির্বাচন কমিশনে জমা হলফনামা ও আয়কর রিটার্নের সম্পদ বিবরণী সঙ্গতিপূর্ণ", meta: "এনবিআর রেকর্ড ও নির্বাচন কমিশনের হলফনামা · এআই কর্তৃক প্রাপ্ত", sources: 2, suggested: "keep" },
  { id: "AI-07", profileId: "KAR-265917", category: "নেতিবাচক", title: "ওয়ার্ড ৩৫-এ অনুদান বিতরণে অনিয়মের অভিযোগে সামাজিক মাধ্যমের পোস্ট", meta: "বেনামি ফেসবুক পেজ · উৎস যাচাই করা যায়নি", sources: 1, suggested: "exclude" },
  { id: "AI-08", profileId: "KAR-814369", category: "ইতিবাচক", title: "নির্বাচন কমিশনের হলফনামায় কোনো ফৌজদারি মামলার তথ্য নেই", meta: "নির্বাচন কমিশনের হলফনামা · এআই কর্তৃক প্রাপ্ত", sources: 1, suggested: "keep" },
  { id: "AI-09", profileId: "KAR-693152", category: "ইতিবাচক", title: "২০২৫–২৬ অর্থবছরে ওয়ার্ড ২২-এ দুটি স্কুল ভবন সংস্কার", meta: "গাজীপুর সিটি কর্পোরেশনের বার্ষিক প্রতিবেদন · এআই কর্তৃক প্রাপ্ত", sources: 1, suggested: "keep" },
];

export function createSeed(): Database {
  return {
    version: DB_VERSION,
    admins: [{ id: "KAR-482915", name: "Razib Khan", initials: "RK", email: "razib.khan@example.com", phone: "01711000001" }],
    // Every account's id is its ALARM ID (KAR- + 6 digits) — the one identifier people use everywhere.
    users: [
      { id: "KAR-482915", role: "admin", phone: "01711000001", password: DEMO_PASSWORD, subjectId: "KAR-482915" },
      ...reviewers.map((r) => ({ id: r.id, role: "reviewer" as const, phone: r.phone, password: DEMO_PASSWORD, subjectId: r.id })),
      ...staff.map((x) => ({ id: x.id, role: "staff" as const, phone: x.phone, password: DEMO_PASSWORD, subjectId: x.id })),
      ...profiles.map((p) => ({ id: p.id, role: "politician" as const, phone: p.phone, password: DEMO_PASSWORD, subjectId: p.id })),
    ],
    profiles,
    submissions,
    disputes: [
      {
        code: "DSP-009",
        submissionCode: "SUB-0412",
        profileId: "KAR-702438",
        reason: "প্রসঙ্গ অসম্পূর্ণ",
        claim: "দরপত্রটি উন্মুক্ত প্রক্রিয়ায় হয়েছে এবং আমি মূল্যায়ন কমিটিতে ছিলাম না — কমিটির কার্যবিবরণী সংযুক্ত।",
        attachments: ["মূল্যায়ন কমিটির কার্যবিবরণী"],
        filedAt: t("2026-09-12", "10:30"),
        state: "Response",
        decidedAt: t("2026-09-14", "12:02"),
        decidedBy: "KAR-482915",
        decisionReason: "কার্যবিবরণী অনুযায়ী তিনি মূল্যায়ন কমিটিতে ছিলেন না — বক্তব্যটি রিপোর্টে যুক্ত হলো। তবে মালিকানার তথ্য নথিভিত্তিক, তাই রিপোর্ট বহাল।",
      },
      {
        code: "DSP-014",
        submissionCode: "SUB-0409",
        profileId: "KAR-702438",
        reason: "তথ্য ভুল",
        claim: "দাখিলা রেকর্ডে যে জমি দেখানো হয়েছে তার ০.৩৩ একর ২০২২ সালে ওয়ারিশসূত্রে হস্তান্তরিত হয়েছে। হস্তান্তরের দলিল ও নামজারির কাগজ সংযুক্ত করেছি।",
        attachments: ["হস্তান্তর দলিল ৪৪৫২/২২", "নামজারি খতিয়ান"],
        filedAt: t("2026-09-21", "10:08"),
        state: "Open",
      },
      {
        code: "DSP-015",
        submissionCode: "SUB-0400",
        profileId: "KAR-265917",
        reason: "প্রসঙ্গ অসম্পূর্ণ",
        claim: "ঠিকাদারি প্রতিষ্ঠানটির মালিকানা ২০২৩ সালেই হস্তান্তর হয়েছে, দরপত্রের সময় আমার পরিবারের কেউ মালিক ছিলেন না। আরজেএসসি-র হালনাগাদ সনদ দিয়েছি।",
        attachments: ["আরজেএসসি হালনাগাদ সনদ, ১৪ সেপ্টেম্বর ২০২৬"],
        filedAt: t("2026-09-23", "09:40"),
        state: "Open",
      },
      {
        code: "DSP-016",
        submissionCode: "SUB-0426",
        profileId: "KAR-693152",
        reason: "অন্যান্য",
        claim: "প্রতিবেদনে ওয়ার্ড ২২-এর দুটি সড়কের কথা বলা হয়েছে, কিন্তু একটি সড়ক ওয়ার্ড ২১-এর — সমাপ্তি প্রতিবেদনে তা স্পষ্ট। সংশোধন চাই।",
        attachments: [],
        filedAt: t("2026-09-24", "08:30"),
        state: "Open",
      },
    ],
    staff,
    assignments: [
      { id: "ASG-01", staffId: "KAR-615283", profileId: "KAR-814369", brief: "হলফনামায় ঘোষিত সম্পদের সাথে ভূমি অফিসের দাখিলা রেকর্ড মিলিয়ে দেখুন। ওয়ার্ড কার্যালয়ের হাজিরা খাতার ছবি নিন।", wards: "ওয়ার্ড ১৩, মিরপুর মডেল", due: "2026-09-29", open: true },
      { id: "ASG-02", staffId: "KAR-615283", profileId: "KAR-693152", brief: "চলতি অর্থবছরের দুটি সড়ক প্রকল্পের বর্তমান অবস্থা ছবিসহ নথিভুক্ত করুন। প্রকল্প সাইনবোর্ডের ছবি বাধ্যতামূলক।", wards: "ওয়ার্ড ২২, গাজীপুর সদর", due: "2026-09-26", open: true },
      { id: "ASG-03", staffId: "KAR-528610", profileId: "KAR-702438", brief: "জলাশয় ভরাট ও ত্রাণ বিতরণ নিয়ে সংগৃহীত তথ্যের দাপ্তরিক নথি সংগ্রহ করুন।", wards: "ওয়ার্ড ১২, ১৪, বোয়ালিয়া", due: "2026-09-27", open: true },
      { id: "ASG-04", staffId: "KAR-274906", profileId: "KAR-265917", brief: "অনুদান বিতরণের তালিকার দাপ্তরিক উৎস খুঁজে বের করুন।", wards: "ওয়ার্ড ১৭, ৩৪, কোতোয়ালী", due: "2026-09-30", open: true },
      { id: "ASG-05", staffId: "KAR-947263", profileId: "KAR-265917", brief: "ড্রেন প্রকল্পের ঠিকাদার মালিকানা হস্তান্তরের নথি যাচাই করুন।", wards: "ওয়ার্ড ৩২, ৩৫, কোতোয়ালী", due: "2026-09-28", open: true },
      { id: "ASG-06", staffId: "KAR-839151", profileId: "KAR-539021", brief: "নতুন অর্থবছরের প্রকল্প তালিকা ও অগ্রগতি সংগ্রহ করুন।", wards: "ওয়ার্ড ৩, ৫, ৭, সদর", due: "2026-10-02", open: true },
      { id: "ASG-07", staffId: "KAR-460372", profileId: "KAR-693152", brief: "ওয়ার্ড ২২-এর স্কুল ভবন সংস্কারের নথি সংগ্রহ করুন।", wards: "ওয়ার্ড ২২, গাজীপুর সদর", due: "2026-10-01", open: true },
      { id: "ASG-08", staffId: "KAR-193847", profileId: "KAR-814369", brief: "মিরপুরের ড্রেনেজ প্রকল্পের অগ্রগতি নথিভুক্ত করুন।", wards: "ওয়ার্ড ১১, ১২, মিরপুর মডেল", due: "2026-09-25", open: true },
      { id: "ASG-09", staffId: "KAR-615283", profileId: "KAR-702438", brief: "সংগ্রহ সম্পন্ন — রাজশাহী থেকে দায়িত্ব স্থানান্তরিত।", wards: "ওয়ার্ড ১২, বোয়ালিয়া", due: "2026-09-10", open: false },
    ],
    reviewers,
    reports: SEED_REPORTS,
    aiFindings,
    parties: [
      { name: "বাংলাদেশ আওয়ামী লীগ", kind: "Party" },
      { name: "বাংলাদেশ জাতীয়তাবাদী দল (বিএনপি)", kind: "Party" },
      { name: "জাতীয় পার্টি", kind: "Party" },
      { name: "বাংলাদেশ জামায়াতে ইসলামী", kind: "Party" },
      { name: "জাতীয় নাগরিক পার্টি (এনসিপি)", kind: "Party" },
      { name: "বাংলাদেশ খেলাফত মজলিস", kind: "Party" },
      { name: "স্বতন্ত্র", kind: "Party" },
      { name: "জাতীয় শ্রমিক লীগ", kind: "Organisation" },
      { name: "সুশাসনের জন্য নাগরিক (সুজন)", kind: "Organisation" },
      { name: "প্রধান নির্বাহী সম্পাদক কর্তৃক শুরু", kind: "Organisation" },
    ],
    settings: {
      org: "ALARM Bangladesh",
      language: "bn",
      timezone: "Asia/Dhaka",
      footer: "ALARM Bangladesh কর্তৃক প্রস্তুত। অননুমোদিত বিতরণ লগে সংরক্ষিত হয়।",
      rules: { sources: 2, dispute: 3, caseload: 6, window: 24 },
      notifications: {
        dispute: { sms: true, email: true },
        overdue: { sms: true, email: false },
        held: { sms: false, email: true },
        caseload: { sms: false, email: true },
        report: { sms: false, email: true },
      },
      permissions: {
        submit: { admin: true, reviewer: false, staff: true },
        editAfter: { admin: false, reviewer: false, staff: false },
        decide: { admin: true, reviewer: true, staff: false },
        editBefore: { admin: true, reviewer: true, staff: false },
        staffNames: { admin: true, reviewer: false, staff: false },
        curate: { admin: true, reviewer: false, staff: false },
        sign: { admin: false, reviewer: true, staff: false },
        share: { admin: true, reviewer: true, staff: false },
        accounts: { admin: true, reviewer: false, staff: false },
        disputes: { admin: true, reviewer: false, staff: false },
      },
      security: { twoFactor: true, timeout: 30 },
    },
    meetings: [
      {
        id: "MTG-003",
        code: "rk7m-2pqz-h4wd",
        title: "অক্টোবরের মাঠ পর্যালোচনা সভা",
        agenda: "১. সেপ্টেম্বরের জমা ও সিদ্ধান্তের সারসংক্ষেপ\n২. বাকি থাকা পর্যালোচনা ও এলাকা বণ্টন\n৩. খোলা অভিযোগের অগ্রগতি",
        scheduledAt: t("2026-10-08", "11:00"),
        createdBy: "KAR-482915",
        createdAt: t("2026-09-28", "16:10"),
        status: "scheduled",
        area: { division: "ঢাকা", district: "ঢাকা", upazila: "", thana: "", ward: "" },
        invitees: ["KAR-736204", "KAR-327548"],
        requests: [{ userId: "KAR-274906", at: t("2026-09-29", "09:40"), note: "বাকলিয়ার কাজের অগ্রগতি জানাতে চাই।", state: "pending" }],
        presence: [],
        attended: [],
        removed: [],
      },
      {
        id: "MTG-002",
        code: "w3nb-8ycu-t6ka",
        title: "রাজনৈতিক কর্মীদের সাথে প্রক্রিয়া পরিচিতি",
        agenda: "প্রোফাইল, কার্যক্রম যোগ করা ও অভিযোগ জানানোর প্রক্রিয়া নিয়ে প্রশ্নোত্তর।",
        scheduledAt: t("2026-10-14", "15:30"),
        createdBy: "KAR-482915",
        createdAt: t("2026-09-30", "12:00"),
        status: "scheduled",
        area: { division: "", district: "", upazila: "", thana: "", ward: "" },
        invitees: [],
        requests: [],
        presence: [],
        attended: [],
        removed: [],
      },
      {
        id: "MTG-001",
        code: "f9xd-4gem-q2vr",
        title: "নির্বাহী সম্পাদক সমন্বয় সভা",
        agenda: "পর্যালোচনার মানদণ্ড ও ৪৮ ঘণ্টার মধ্যে সিদ্ধান্ত দেওয়ার নিয়ম।",
        scheduledAt: t("2026-09-22", "10:00"),
        createdBy: "KAR-482915",
        createdAt: t("2026-09-18", "14:20"),
        status: "ended",
        startedAt: t("2026-09-22", "10:02"),
        endedAt: t("2026-09-22", "10:41"),
        area: { division: "ঢাকা", district: "", upazila: "", thana: "", ward: "" },
        invitees: ["KAR-736204", "KAR-158392", "KAR-904617", "KAR-327548"],
        requests: [],
        presence: [],
        attended: ["KAR-482915", "KAR-736204", "KAR-158392", "KAR-327548"],
        removed: [],
      },
    ],
    audit: [
      { at: t("2026-09-24", "09:15"), actor: "KAR-615283", action: "Submitted evidence", target: "SUB-0427" },
      { at: t("2026-09-24", "08:30"), actor: "KAR-693152", action: "Filed dispute", target: "DSP-016" },
      { at: t("2026-09-23", "18:37"), actor: "KAR-482915", action: "Assigned executive editor coverage", target: "KAR-158392" },
      { at: t("2026-09-23", "10:20"), actor: "KAR-702438", action: "Added own activity", target: "SUB-0428" },
      { at: t("2026-09-23", "09:40"), actor: "KAR-265917", action: "Filed dispute", target: "DSP-015" },
      { at: t("2026-09-22", "15:10"), actor: "KAR-528610", action: "Submitted evidence", target: "SUB-0422" },
      { at: t("2026-09-21", "10:08"), actor: "KAR-702438", action: "Filed dispute", target: "DSP-014" },
      { at: t("2026-09-16", "10:24"), actor: "KAR-736204", action: "Approved and signed report", target: "RPT-2026-0039" },
      { at: t("2026-09-14", "12:02"), actor: "KAR-482915", action: "Decided dispute — response added", target: "DSP-009" },
      { at: t("2026-08-26", "17:40"), actor: "KAR-482915", action: "Suspended account", target: "KAR-193847" },
    ],
  };
}
